/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class HelloWorldJNI */

#ifndef _Included_HelloWorldJNI
#define _Included_HelloWorldJNI
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     HelloWorldJNI
 * Method:    sayHello
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_HelloWorldJNI_sayHello
  (JNIEnv *, jobject);

/*
 * Class:     HelloWorldJNI
 * Method:    startProbe
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_HelloWorldJNI_startProbe
  (JNIEnv *, jobject);

/*
 * Class:     HelloWorldJNI
 * Method:    stopProbe
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_HelloWorldJNI_stopProbe
  (JNIEnv *, jobject);

/*
 * Class:     HelloWorldJNI
 * Method:    addToCollection
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_HelloWorldJNI_addToCollection  (JNIEnv *, jobject);

/*
 * Class:     HelloWorldJNI
 * Method:    deleteFromCollection
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_HelloWorldJNI_deleteFromCollection
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
